# version: '3.8'

services:
  # CỤM 1: BACKEND NODE.JS
  backend:
    build: 
      context: ./Backend    # Trỏ vào thư mục lấy Dockerfile
    container_name: message_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      # Truyền biến môi trường trực tiếp, đè lên file .env
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    depends_on:
      - mongodb # Đợi Database chạy lên rồi mới chạy Node.js

  # CỤM 2: DATABASE MONGODB
  mongodb:
    image: mongo:7
    container_name: message_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
